### ISSUE TITLE
请问您的GL-INET AR750S固件编译配置是怎样的呢？谢谢！

### ISSUE THREAD

**Issue by PilotSnail** [Biobots/OpenwrtImgs#1]
如题，我反复用LEDE的代码编译，选择ATH79总是显示编译不成功，必须选择ar71xx才行，求助，谢谢！

**Comment by b1060t** [comment]
如果指的是lean的lede的话，上游openwrt源码现在已经支持选择ath79编译了，可以尝试把lede独有的插件复制到openwrt源码下编译，可能会有些兼容问题，具体的我这里也记不清了，多试试应该还是能编过的
ath79用的是dts文件来描述硬件，跟ar71xx差别比较大，具体可以参考这个pull request
https://github.com/openwrt/openwrt/pull/2184#issue-293126510
